import{useCallback,useEffect,useRef,useState}from"react"
import type{AgentEvent,AuditEvent,Diagnosis,Investigation,RecoveryPlan,RenderState,TelemetryPoint,VerificationComparison,WhatIfResult}from"@/lib/types"

const API_ROOT=import.meta.env.VITE_SIMULATOR_API_ROOT||"/api/simulator"
const AGENT_ROOT=import.meta.env.VITE_AGENT_API_ROOT||"/api/agent"
const AGENT_APP="production_director_agent",AGENT_USER="operator-dashboard"

async function request<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(`${API_ROOT}${path}`,{...init,headers:{"Content-Type":"application/json",...init?.headers}});if(!response.ok)throw new Error(await response.text()||`Request failed with ${response.status}`);return response.json() as Promise<T>}
const initialSteps=()=>[{id:"metrics",label:"Query Grafana metrics",status:"running" as const},{id:"logs",label:"Search Scene 87 logs",status:"idle" as const},{id:"traces",label:"Inspect correlated render trace",status:"idle" as const},{id:"impact",label:"Calculate deterministic delivery impact",status:"idle" as const}]
const toolStep:Record<string,string>={grafana_query_metrics:"metrics",grafana_query_logs:"logs",grafana_query_traces:"traces",calculate_delivery_impact:"impact"}

export function useOperations(){
 const[diagnosis,setDiagnosis]=useState<Diagnosis|null>(null),[agentDiagnosis,setAgentDiagnosis]=useState<Diagnosis|null>(null),[plans,setPlans]=useState<RecoveryPlan[]>([]),[audit,setAudit]=useState<AuditEvent[]>([]),[state,setState]=useState<RenderState|null>(null),[telemetry,setTelemetry]=useState<TelemetryPoint[]>([]),[investigation,setInvestigation]=useState<Investigation|null>(null),[verification,setVerification]=useState<VerificationComparison>({available:false}),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false)
 const inFlight=useRef(false),sessionId=useRef<string|null>(null),realAgentActive=useRef(false),diagnosisRef=useRef<Diagnosis|null>(null)
 const refresh=useCallback(async()=>{if(inFlight.current)return;inFlight.current=true;try{const[d,p,a,s,h,i,v]=await Promise.all([request<Diagnosis>("/diagnosis"),request<{plans:RecoveryPlan[]}>("/recovery-plans"),request<{events:AuditEvent[]}>("/audit-log?limit=25"),request<RenderState>("/simulation/status"),request<{points:Array<{timestamp:string;gpu_memory_utilization:number;queue_depth:number}>}>("/telemetry-history?limit=72"),request<Investigation>("/agent/investigation"),request<VerificationComparison>("/verification/comparison")]);diagnosisRef.current=d;setDiagnosis(d);setPlans(p.plans);setAudit(a.events);setState(s);setVerification(v);if(!realAgentActive.current)setInvestigation(i);setTelemetry(h.points.map(point=>({time:new Date(point.timestamp).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}),memory:point.gpu_memory_utilization,queue:point.queue_depth})));setError(null)}catch(reason){setError(reason instanceof Error?reason.message:"Unable to reach the simulator")}finally{inFlight.current=false}},[])
 useEffect(()=>{const initial=window.setTimeout(()=>void refresh(),0),timer=window.setInterval(()=>void refresh(),2000);return()=>{window.clearTimeout(initial);window.clearInterval(timer)}},[refresh])

 const updateTool=useCallback((tool:string,complete:boolean,response?:unknown)=>{const target=toolStep[tool];if(!target)return;setInvestigation(current=>{const steps=(current?.steps??initialSteps()).map(step=>step.id===target?{...step,status:complete?"complete" as const:"running" as const}:step);const evidence:Record<string,string>={};if(complete&&tool==="grafana_query_metrics")evidence.metric="PromQL render telemetry · Grafana MCP";if(complete&&tool==="grafana_query_logs")evidence.log="Scene 87 CUDA out of memory · Loki";if(complete&&tool==="grafana_query_traces"){const match=JSON.stringify(response).match(/[a-f0-9]{32}/);evidence.trace=match?`Tempo trace ${match[0].slice(0,12)}…`:"incident.gpu_oom · Tempo"}return{mode:"gemini-grafana-mcp",workflow_state:"INVESTIGATING",steps,evidence:{...(current?.evidence??{}),...evidence}}})},[])

 const runAgent=useCallback(async(prompt:string,phase:"investigate"|"verify")=>{if(!sessionId.current){sessionId.current=globalThis.crypto?.randomUUID?.()??`local-${Date.now()}`;const created=await fetch(`${AGENT_ROOT}/apps/${AGENT_APP}/users/${AGENT_USER}/sessions/${sessionId.current}`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});if(!created.ok)throw new Error(`Unable to create the local agent session (${created.status})`)}realAgentActive.current=true;if(phase==="investigate")setInvestigation({mode:"gemini-grafana-mcp",workflow_state:"INVESTIGATING",steps:initialSteps(),evidence:{}});const response=await fetch(`${AGENT_ROOT}/run_sse`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({appName:AGENT_APP,userId:AGENT_USER,sessionId:sessionId.current,newMessage:{role:"user",parts:[{text:prompt}]}})});if(!response.ok||!response.body)throw new Error(await response.text()||"Agent investigation failed");const reader=response.body.getReader(),decoder=new TextDecoder();let buffer="",finalText="";while(true){const{done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split("\n");buffer=lines.pop()??"";for(const line of lines){if(!line.startsWith("data:"))continue;const event=JSON.parse(line.slice(5)) as AgentEvent;for(const part of event.content?.parts??[]){if(part.functionCall)updateTool(part.functionCall.name,false);if(part.functionResponse)updateTool(part.functionResponse.name,true,part.functionResponse.response);if(part.text)finalText=part.text}}}if(phase==="investigate"){const base=diagnosisRef.current;if(base)setAgentDiagnosis({...base,root_cause:finalText.split("\n").find(line=>line.replaceAll("*","").trim().length>40)?.replaceAll("*","").trim()??"Gemini correlated Scene 87 GPU memory exhaustion across Grafana evidence.",source:"gemini-grafana-mcp"});setInvestigation(current=>current?{...current,workflow_state:"DECISION_REQUIRED",steps:current.steps.map(step=>({...step,status:"complete"}))}:current)}},[updateTool])

 const act=useCallback(async(path:string)=>{setBusy(true);try{await request(path,{method:"POST"});await refresh()}finally{setBusy(false)}},[refresh])
 const reset=useCallback(async()=>{realAgentActive.current=false;sessionId.current=null;setAgentDiagnosis(null);setInvestigation(null);await act("/simulation/reset")},[act])
 const inject=useCallback(async(kind:"gpu-oom"|"corrupted-asset"="gpu-oom")=>{setBusy(true);try{await request(`/simulation/incidents/${kind}`,{method:"POST"});await refresh();if(kind==="gpu-oom")void runAgent("Investigate the active Project Nova incident. Query Grafana MCP metrics, logs, and traces once each, calculate deterministic impact, and recommend recovery options. Do not request approval or execute recovery.","investigate").catch(reason=>{const message=reason instanceof Error?reason.message:"agent unavailable";realAgentActive.current=true;setInvestigation(current=>({...current!,mode:`mock-fallback · ${message}`}))})}finally{setBusy(false)}},[refresh,runAgent])
 const approve=useCallback(async(action:string)=>{setBusy(true);try{const approval=await request<{id:string}>(`/approvals?action=${encodeURIComponent(action)}`,{method:"POST"});if(sessionId.current)await runAgent(`The human operator approves ${action}. Use approval ID ${approval.id} to execute only that action. Then query Grafana metrics, logs, and traces again and call verify_recovery before reporting the result.`,"verify");else await request(`/recovery/${action}`,{method:"POST",body:JSON.stringify({approval_id:approval.id,approved_by:"operator-dashboard"})});await refresh();return{execution_id:approval.id}}finally{setBusy(false)}},[refresh,runAgent])
 const simulateFailure=useCallback(()=>request<{armed:boolean}>("/simulation/recovery/fail-next",{method:"POST"}).then(()=>undefined),[])
 const whatIf=useCallback((input:{workers_added:number;deadline_minutes:number;quality_percent:number;prioritize_critical:boolean})=>request<WhatIfResult>("/impact/what-if",{method:"POST",body:JSON.stringify(input)}),[])
 const demo=useCallback(async()=>{await reset();await new Promise(resolve=>setTimeout(resolve,700));await inject("gpu-oom")},[inject,reset])
 return{diagnosis:agentDiagnosis??diagnosis,plans,audit,state,telemetry,investigation,verification,error,busy,refresh,approve,start:()=>act("/simulation/start"),reset,inject,simulateFailure,whatIf,demo}
}
