import {useCallback,useEffect,useRef,useState} from "react"
import type {AuditEvent,Diagnosis,Incident,RecoveryExecution,RecoveryPlan,RenderState,TelemetryPoint} from "@/lib/types"
const API_ROOT="/api/simulator"
async function readJson<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(`${API_ROOT}${path}`,init);if(!response.ok)throw new Error(await response.text()||`Request failed with ${response.status}`);return response.json() as Promise<T>}
export function useOperations(){
 const [diagnosis,setDiagnosis]=useState<Diagnosis|null>(null),[plans,setPlans]=useState<RecoveryPlan[]>([]),[audit,setAudit]=useState<AuditEvent[]>([]),[incidents,setIncidents]=useState<Incident[]>([]),[executions,setExecutions]=useState<RecoveryExecution[]>([]),[state,setState]=useState<RenderState|null>(null),[telemetry,setTelemetry]=useState<TelemetryPoint[]>([]),[error,setError]=useState<string|null>(null),[isApproving,setIsApproving]=useState(false);const inFlight=useRef(false)
 const refresh=useCallback(async()=>{if(inFlight.current)return;inFlight.current=true;try{const [d,p,a,i,x,s,h]=await Promise.all([readJson<Diagnosis>("/diagnosis"),readJson<{plans:RecoveryPlan[]}>("/recovery-plans"),readJson<{events:AuditEvent[]}>("/audit-log?limit=50"),readJson<{incidents:Incident[]}>("/incidents?limit=100"),readJson<{executions:RecoveryExecution[]}>("/recovery-executions?limit=100"),readJson<RenderState>("/state"),readJson<{points:Array<{timestamp:string;gpu_memory_utilization:number;queue_depth:number}>}>("/telemetry-history?limit=72")]);setDiagnosis(d);setPlans(p.plans);setAudit(a.events);setIncidents(i.incidents);setExecutions(x.executions);setState(s);setTelemetry(h.points.map(point=>({time:new Date(point.timestamp).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}),memory:point.gpu_memory_utilization,queue:point.queue_depth})));setError(null)}catch(reason){setError(reason instanceof Error?reason.message:"Unable to reach the simulator")}finally{inFlight.current=false}},[])
 useEffect(()=>{void refresh();const interval=window.setInterval(()=>void refresh(),5000);return()=>window.clearInterval(interval)},[refresh])
 const approve=useCallback(async(planId:string)=>{setIsApproving(true);try{const result=await readJson<{execution_id:string}>(`/recovery-plans/${planId}/approve?approved_by=operator-dashboard`,{method:"POST"});await refresh();return result}finally{setIsApproving(false)}},[refresh])
 const getIncidentPlans=useCallback((incidentId:string)=>readJson<{can_execute:boolean;plans:RecoveryPlan[]}>(`/incidents/${incidentId}/recovery-plans`),[])
 const approveIncident=useCallback(async(incidentId:string,planId:string)=>{setIsApproving(true);try{const result=await readJson<{execution_id:string}>(`/incidents/${incidentId}/recovery-plans/${planId}/approve?approved_by=operator-dashboard`,{method:"POST"});await refresh();return result}finally{setIsApproving(false)}},[refresh])
 return{diagnosis,plans,audit,incidents,executions,state,telemetry,error,isApproving,refresh,approve,getIncidentPlans,approveIncident}
}
